package ch.samt.main;

import ch.samt.dictionary.Dictionary;
import ch.samt.dictionary.Entry;

public class App {
    public static void main(String[] args) {
        Dictionary d = new Dictionary();
        d.aggiungi(new Entry("Cane","Dog"));
        d.aggiungi(new Entry("Gatto","Cat"));
        d.aggiungi(new Entry("Casa","House"));
        d.aggiungi(new Entry("Libro","Book"));
        d.aggiungi(new Entry("Penna","Pen"));
        d.aggiungi(new Entry("Mela","Apple"));
        d.aggiungi(new Entry("Sedia","Chair"));
        d.aggiungi(new Entry("Tavolo","Table"));
        d.aggiungi(new Entry("Finestra","Window"));
        d.aggiungi(new Entry("Porta","Door"));
        d.aggiungi(new Entry("Acqua","Water"));
        d.aggiungi(new Entry("Pane","Bread"));
        d.aggiungi(new Entry("Cielo","Sky"));
        d.aggiungi(new Entry("Sole","Sun"));
        d.aggiungi(new Entry("Luna","Moon"));
        d.aggiungi(new Entry("Stella","Star"));
        d.aggiungi(new Entry("Fiore","Flower"));
        d.aggiungi(new Entry("Albero","Tree"));
        d.aggiungi(new Entry("Strada","Road"));
        d.aggiungi(new Entry("Auto","Car"));
        d.aggiungi(new Entry("Bicicletta","Bicycle"));
        d.aggiungi(new Entry("Treno","Train"));
        d.aggiungi(new Entry("Aereo","Airplane"));
        d.aggiungi(new Entry("Scuola","School"));
        d.aggiungi(new Entry("Classe","Classroom"));
        d.aggiungi(new Entry("Insegnante","Teacher"));
        d.aggiungi(new Entry("Studente","Student"));
        d.aggiungi(new Entry("Gioco","Game"));
        d.aggiungi(new Entry("Telefono","Phone"));
        d.aggiungi(new Entry("Computer","Computer"));
        d.aggiungi(new Entry("Tazza","Cup"));
        d.aggiungi(new Entry("Piatto","Plate"));
        d.aggiungi(new Entry("Cucchiaio","Spoon"));
        d.aggiungi(new Entry("Forchetta","Fork"));
        d.aggiungi(new Entry("Coltello","Knife"));
        d.aggiungi(new Entry("Letto","Bed"));
        d.aggiungi(new Entry("Divano","Sofa"));
        d.aggiungi(new Entry("Lampada","Lamp"));
        d.aggiungi(new Entry("Specchio","Mirror"));
        d.aggiungi(new Entry("Orologio","Clock"));
        d.aggiungi(new Entry("Scarpa","Shoe"));
        d.aggiungi(new Entry("Pantaloni","Pants"));
        d.aggiungi(new Entry("Maglietta","T-shirt"));
        d.aggiungi(new Entry("Cappotto","Coat"));
        d.aggiungi(new Entry("Cappello","Hat"));
        d.aggiungi(new Entry("Occhiali","Glasses"));
        d.aggiungi(new Entry("Borsa","Bag"));
        d.aggiungi(new Entry("Chiave","Key"));
        d.aggiungi(new Entry("Soldi","Money"));
        d.aggiungi(new Entry("Negozio","Shop"));
        d.aggiungi(new Entry("Mercato","Market"));
        d.aggiungi(new Entry("Città","City"));
        d.aggiungi(new Entry("Villaggio","Village"));
        d.aggiungi(new Entry("Montagna","Mountain"));
        d.aggiungi(new Entry("Mare","Sea"));
        d.aggiungi(new Entry("Fiume","River"));
        d.aggiungi(new Entry("Lago","Lake"));
        d.aggiungi(new Entry("Foresta","Forest"));
        d.aggiungi(new Entry("Animale","Animal"));
        d.aggiungi(new Entry("Uccello","Bird"));
        d.aggiungi(new Entry("Pesce","Fish"));
        d.aggiungi(new Entry("Cavallo","Horse"));
        d.aggiungi(new Entry("Mucca","Cow"));
        d.aggiungi(new Entry("Pecora","Sheep"));
        d.aggiungi(new Entry("Maiale","Pig"));
        d.aggiungi(new Entry("Topo","Mouse"));
        d.aggiungi(new Entry("Serpente","Snake"));
        d.aggiungi(new Entry("Farfalla","Butterfly"));
        d.aggiungi(new Entry("Insetto","Insect"));
        d.aggiungi(new Entry("Cibo","Food"));
        d.aggiungi(new Entry("Bevanda","Drink"));
        d.aggiungi(new Entry("Colazione","Breakfast"));
        d.aggiungi(new Entry("Pranzo","Lunch"));
        d.aggiungi(new Entry("Cena","Dinner"));
        d.aggiungi(new Entry("Famiglia","Family"));
        d.aggiungi(new Entry("Madre","Mother"));
        d.aggiungi(new Entry("Padre","Father"));
        d.aggiungi(new Entry("Sorella","Sister"));
        d.aggiungi(new Entry("Fratello","Brother"));
        d.aggiungi(new Entry("Nonna","Grandmother"));
        d.aggiungi(new Entry("Nonno","Grandfather"));
        d.aggiungi(new Entry("Bambino","Child"));
        d.aggiungi(new Entry("Amico","Friend"));
        d.aggiungi(new Entry("Persona","Person"));
        d.aggiungi(new Entry("Corpo","Body"));
        d.aggiungi(new Entry("Testa","Head"));
        d.aggiungi(new Entry("Mano","Hand"));
        d.aggiungi(new Entry("Piede","Foot"));
        d.aggiungi(new Entry("Occhio","Eye"));
        d.aggiungi(new Entry("Orecchio","Ear"));
        d.aggiungi(new Entry("Bocca","Mouth"));
        d.aggiungi(new Entry("Naso","Nose"));
        d.aggiungi(new Entry("Lavoro","Job"));
        d.aggiungi(new Entry("Ufficio","Office"));
        d.aggiungi(new Entry("Compito","Task"));
        d.aggiungi(new Entry("Tempo","Time"));
        d.aggiungi(new Entry("Giornata","Day"));
        d.aggiungi(new Entry("Settimana","Week"));
        d.aggiungi(new Entry("Anno","Year"));

        System.out.println(d.cerca("Gatto"));
        d.stampaTutto();
        System.out.println(d.cerca("Sole"));
    }
}